
---
title: "Materiales"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, cache=TRUE)
```

<style type="text/css">
h1 {
  font-size: 32px;
}
h2 {
  font-size: 24px;
}
p, li {
  font-size: 16px;
}
</style>



Acá puede encontrar los materiales del curso[.](materials/Kurlat Course in Modern Macroeconomics.pdf) 
<br>

# Programa (Syllabus)

La versión más reciente del programa del curso [acá.](materials/2025EC3201_I.pdf)

<br>


## Tesis 1: Enfoque intertemporal del consumo y ahorro

<br>

### Repaso matemático

* Apéndice A [GLS]
* [Práctica 0](materials/PS0_2024.pdf) 

### Repaso macroeconomía básica

* Capítulos 9, 10, 11, 12 y 13 [J] 
* [Notas](materials/Notas_repaso_macro1.pdf) Versión 1.0. 


### Decisiones óptimas de consumo y ahorro en un marco de dos periodos

* Capítulo 9 [GLS], Capítulo 6 [K]
* [Notas](materials/Notas_consumo.pdf) *Nueva versión!*   
* [Práctica 1](materials/PS1.pdf)

### Modelo de consumo y ahorro con múltiples periodos

* Capítulo 10 [GLS], Capítulo 6 [K]
* [Práctica 2](materials/PS2.pdf)
* [Notas adicionales](materials/Consumo_adicionales_v2.pdf)
* [Tarea 1](materials/PS1_25.pdf) (Entrega: 10 de abril) [Datos Stata](materials/data_consumo_psid.dta) [Datos Excel](materials/data_consumo_psid.csv). 
* [Subir Tarea 1](https://www.dropbox.com/request/BdXuATo47U3QmDWA4UB4) 



 
<br>

## Tesis 2: Equilibrio competitivo con producción, gobierno y dinero

<br>

### Un modelo macroeconómico de equilibrio general sencillo
* Capítulo 7.2 [K] (modelo laboral estático)
* [Notas](materials/static_ge.pdf)
* [Práctica 3](materials/PS3_2.pdf) 


### Decisiones de trabajo y ocio

* Capítulo 12.2 [GLS], Capítulo 7 [K]
* [Notas](materials/Modelo_ocio.pdf)
* [Práctica 4](materials/PS4.pdf)  
* [Adicionales](materials/LaborSupply.pdf)


### Decisiones de producción de la empresa

* Capítulo 12.1 [GLS], Capítulo 8 [K]
* [Notas](materials/Modelo_produccion.pdf) 
* [Práctica 5](materials/PS3.pdf)

### Equilibrio competitivo 

* Capítulos 12.3 y 12.4 [GLS], Capítulo 9 [K]
* [Notas](materials/Modelo_equilibrio.pdf) 
* [Práctica 6](materials/PS_GE.pdf)  

## Primer Parcial

* Fecha: 8 de mayo.
* [Práctica](materials/MT1_practica.pdf) 
* [I Parcial I-2023](materials/MT1.pdf). [Soluciones](materials/MT1_sol.pdf) 
* [I Parcial II-2023](materials/MT12.pdf). [Soluciones](materials/MT12_sol.pdf)
* [I Parcial I-2024](materials/mt1_1_24.pdf). [Soluciones](materials/mt1_124_sol.pdf)
* [I Parcial II-2024](materials/MT1_2_24.pdf). [Soluciones](materials/MT1_2_24_sol.pdf)
* [I Parcial I-2025](materials/MT1_I25.pdf). [Soluciones](materials/MT1_I25_sol.pdf)


### Economía de producción con gobierno

* Capítulos 13 [GLS]
* [Notas](materials/Politica_Fiscal.pdf)
* [Práctica 7](materials/PSGobierno.pdf)  


### Economía de producción con dinero

* Capítulos 14, 21 y 32 [GLS], Capítulo 10 y 11 [K]
* Notas: [Demanda Monetaria](materials/Modelo_dinero.pdf). [Oferta Monetaria](materials/MoneySupply.pdf)




<br>

## Tesis 3: El ciclo económico 

<br>


### Modelo de Ciclo Económico Real de dos periodos (RBC)

* Capítulos 18 y 19 [GLS], Capítulo 12 [K]
* [Práctica 8](materials/PSRBC1.pdf)

### Eficiencia del equilibrio

* Capítulos 15 [GLS]
* [Práctica 9](materials/PSSPP.pdf)

### Hechos estilizados del ciclo económico

* Capítulo 20.1 [GLS]
* [Notas filtros](materials/Notas_filtros.pdf). [Notas Ciclo Económico Real](materials/Notas_rbc.pdf) 
* [Tarea 2](materials/Tarea2_25.pdf) (Entrega: 30 de mayo) 

### Implicaciones de política y críticas al modelo neoclásico

* Capítulos 22 [GLS]
* [Práctica 10](materials/PS102.pdf)

<!-- ### Modelo Neoclásico con economía abierta -->

<!-- * Capítulos 23 [GLS] -->
<!-- * [Práctica 9](materials/PS9.pdf)  -->


## Segundo Parcial

* Fecha: (12 de junio)
* [Práctica](materials/MT2_practica.pdf) 
* [II Parcial I-2023](materials/SegundoParcialMacro2.pdf) [Soluciones](materials/MT2_sol.pdf) 
* [II Parcial II-2023](materials/MT2_22023.pdf) [Soluciones](materials/mt2223_sol.pdf) 
* [II Parcial II-2024](materials/MT2-2-24.pdf). [Soluciones](materials/MT2-2-24-SOL.pdf)
* [II Parcial I-2025](materials/MT2_I25.pdf). [Soluciones](materials/mt2_I25_sol.pdf)

### Modelo Neokeynesiano 

* Capítulos 24 y 25 [GLS], Capítulo 14 [K]
* [Notas sobre implementación política monetaria](materials/implementacion_mp.pdf).

### Efecto de choques bajo el modelo Neokeynesiano

* Capítulo 26 [GLS], Capítulo 14 [K]
 

### Dinámica de transición entre el corto y mediano plazo

* Capítulo 27 [GLS]
* [Práctica 11](materials/PS112.pdf)

### Modelo macroeconómico con economía abierta

* Capítulo 23 y 30 [GLS]
* Práctica 12: GLS Capítulo 24 (1, 2, 3 y 4) y capítulo 30 (1, 2, 3)

<br>




## Tesis 4: Políticas de estabilización macroeconómica

<br>


### Política monetaria y fiscal bajo el modelo Neokeynesiano

* Capítulo 28 [GLS], Capítulo 15 [K]
* [Neutralidad monetaria y rigideces nominales](materials/money_neutrality.pdf)
* [Práctica 13](materials/PS132.pdf)
* [Notas reglas de política](materials/taylor_notes.pdf)
* Romer, C. D., & Romer, D. H. (2023). Does Monetary Policy Matter? The Narrative Approach after 35 Years (No. w31170). National Bureau of Economic Research. [Descargar](materials/Readings/romerromer2023.pdf) 
* Nakamura, E., & Steinsson, J. (2013). Price rigidity: Microeconomic Evidence and Macroeconomic Implications. Annu. Rev. Econ., 5(1), 133-163. [Descargar](materials/Readings/price_rigidity.pdf) 

 

### Límite inferior cero (Zero Lower Bound)

* Capítulos 29 [GLS]
* [Práctica 14](materials/PS14.pdf) 
<!-- * [Tarea 5](materials/Tarea5Macro2.pdf) (Entrega: 29 de noviembre) [Datos Stata](materials/data_tarea5.dta) [Datos Excel](materials/data_tarea5.xlsx)  -->


### Crisis financieras
* Notas [Fricciones Financieras y Amplificación](materials/financial_amplification.pdf)
* Notas [Crisis Financieras](materials/CrisisFinancieras.pdf) (Caps 31 y 37 [GLS])

## Tercer Parcial

* [Práctica](materials/MT3_practice.pdf) 
* [III Parcial I-2023](materials/MT3.pdf) 
* [III Parcial II-2023](materials/MT3_22023.pdf)
* [III Parcial I-2024](materials/III_Macro2_I24.pdf)  [Soluciones](materials/sol_mt3_I24.pdf)

