---
title: "Referencias"
output: html_document
---
<br>

### Referencias bibliográficas

* [*International Macroeconomics: A Modern Approach*](https://press.princeton.edu/books/hardcover/9780691170640/international-macroeconomics) de Stephanie Schmitt-Grohé, Martín Uribe y Michael Woodford.
* [*Open Economy Macroeconomics*](https://press.princeton.edu/books/hardcover/9780691158778/open-economy-macroeconomics) de Stephanie Schmitt-Grohé y Martín Uribe.
* [*Foundations of International Macroeconomics*](https://mitpress.mit.edu/books/foundations-international-macroeconomics#:~:text=Foundations%20of%20International%20Macroeconomics%20is,open%20economy%20macroeconomics%20and%20finance.) de Maurice Obstfeld y Kenneth Rogoff.
* [*Intermediate Macroeconomics*](https://www3.nd.edu/~esims1/GLS_may_2021.pdf) de Julio Garín, Robert Lester y Eric Sims 
<br>

### Datos

* [The external wealth of nations database](https://www.brookings.edu/research/the-external-wealth-of-nations-database/) 
* Indicadores económicos del [BCCR](https://www.bccr.fi.cr/indicadores-economicos)
* World Economic Outlook Database [Abril 2022](https://www.imf.org/en/Publications/WEO/weo-database/2022/April)
<br>
* FRED [data](https://fred.stlouisfed.org/)
* Penn World Tables [10.01](https://www.rug.nl/ggdc/productivity/pwt/?lang=en)

### Lecturas recomendadas

<br>

#### Consumo y ahorro

* Allen, F. and D. Gale (2007): Understanding Financial Crises, Oxford University Press, Oxford, England. (capítulo 2.1)
* Moss, D.A. (2002): When All Else Fails: The Government as the Ultimate Risk Manager, Harvard University Press, Cambridge, MA. (capítulo 5)
* Mankiw, N.G. (2009): Macroeconomics, Worth Publishers, New York, NY. (7th edition) (capítulo 17)
* Barro, R.J. (1997): Macroeconomics, MIT Press, Cambridge, MA. (5th edition) (capítulo 3)
* Carrol, C.D. (2001): “A Theory of the Consumption Function, with and without Liquidity Constraints,” Journal of Economic Perspectives, 15(3), 23-45. [Descargar](materials/Readings/Carroll2001.pdf)
* Angeletos, G.M., D. Laibson, A. Repetto, J. Tobacman and S. Weinberg (2001): “The Hyperbolic Consumption Model: Calibration, Simulation, and Empirical Evidence,” Journal of Economic Perspectives, 15(3), 47-68. [Descargar](materials/Readings/Angeletos2001.pdf)
* **Gourinchas, P.O. and J.A. Parker (2002): “Consumption over the Life Cycle,” Econometrica, 70(1), 47-89. [Descargar](materials/Readings/GourinchasParker2002.pdf)**

#### Oferta laboral

* Martinez, I. Z., Saez, E., & Siegenthaler, M. (2021). Intertemporal labor supply substitution? Evidence from the swiss income tax holidays. American Economic Review, 111(2), 506-546. [Descargar](materials/Readings/martinez-saez-siegenthalerAER21.pdf)

* Sigurdsson, J. (2022). Labor supply responses and adjustment frictions: A tax-free year in Iceland. Working Paper. [Descargar](materials/Readings/sigurdsson.pdf)


